version: 2
project_name: taiwan-food-nutrition

builds:
  - skip: true

release:
  extra_files:
    - glob: nutrition.db
    - glob: USAGE.md

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
